apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: theia-beraldo
  labels:
    app: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
      - name: volume-theia-beraldo
        persistentVolumeClaim:
          claimName: volume-theia-beraldo
      containers:
      - image: theiaide/theia:1.0.0
        name: theia
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /home/project
          name: volume-theia-beraldo
