apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: entrada-theia
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: theia.beraldo.jacstack.jacexperts.io
    http:
      paths:
      - backend:
          serviceName: srv-theia
          servicePort: 80