apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: depl-theia-beraldo
  labels:
    app: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: theia
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      volumes:
      - name: volume-theia-beraldo
        persistentVolumeClaim:
           claimName: volume-theia-beraldo
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: theia
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - mountPath: /home/project
          name: volume-theia-beraldo

