apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-theia-beraldo
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem

